name: build and test
on:
  push:
    branches: [ master ]
    paths: 
    - 'src/**'
    - '.github/workflows/JunitReport.yml'


jobs:
  build:
    name: Build and Run Junit Reporting Tool
    runs-on: ubuntu-latest
    steps:
      - name: JUNIT Test Report Tool
        uses: JohnMeyerhoff/JunitAnnotations@v1.0.0
        with:
          source_dir: './src'
